version: '2'
services:
    ngjava-app:
        image: ngjava
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ngjava-postgresql:5432/ngjava
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    ngjava-postgresql:
        extends:
            file: postgresql.yml
            service: ngjava-postgresql
